### ISSUE TITLE
Profile picture can neither be changed nor removed

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#1]
When I click to change or remove the profile picture, absolutely nothing happens.

**Comment by wingertge** [comment]
Implemented in 8c91899, after a lot of work.

**Comment by Giftpflanze** [comment]
I still can’t remove the picture by clicking on the X.

**Comment by wingertge** [comment]
That's not implemented yet since we don't currently have a default profile picture. I'll remove the x in the next commit.
