### ISSUE TITLE
Can't add tags

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#12]
Entering a tag and leaving the text field deletes the tag, be it by clicking into the deck name text field or clicking the save button.

**Comment by wingertge** [comment]
This is part of the way the tag field works, you have to press enter to add the tag. I can enable add on blur to add it when leaving the field, but I'm not sure if that is more intuitive or annoying.

**Comment by Giftpflanze** [comment]
Oh, I would never have thought to press enter.

**Comment by wingertge** [comment]
Set blur behaviour to add to see if it's more intuitive. Another option is to keep input on blur and still add on Enter. Would appreciate feedback on how this feels.

**Comment by Giftpflanze** [comment]
OK, so I would add a button to add a tag or a description that explains you have to press enter to add a tag.
