### ISSUE TITLE
Can't learn other users’ decks

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#19]
After clicking on the heart of a deck of another user, I should be able to learn the cards (this fact should be communicated somewhere, btw). However, I am not asked to review them.

**Comment by wingertge** [comment]
Fixed in 7512a40

**Comment by Giftpflanze** [comment]
I removed the decks, added them, logged out and in and then it worked.

**Comment by wingertge** [comment]
Should be working going forward.
