### ISSUE TITLE
content is not refreshing after submitting posts on profile page

### ISSUE THREAD

**Issue by Askath** [wingertge/project-memory-issues#22]
Steps to reproduce:

Profile -> Type message in text area -> post.

Expected: page should refresh and show new post
result: nothing happenes

Same behavior when pressing the delete button of posts

**Comment by wingertge** [comment]
This is a bug in Apollo Client, it was working previously. I'll see if a downgrade fixes it.

**Comment by wingertge** [comment]
Seems to be fixed after upgrading to the alpha version of apollo-react-hooks
