### ISSUE TITLE
Responsive design breaks in help view when display width < 960 px.

### ISSUE THREAD

**Issue by Askath** [wingertge/project-memory-issues#23]
Sidebar overlaps with most of the shown text and makes it unable to read it properly.
![example](https://user-images.githubusercontent.com/42957914/57928737-e0f1d380-78b1-11e9-9114-f181f9b2da6d.PNG)

**Comment by wingertge** [comment]
There was a mismatch in the drawer behaviour vs drawer rendering. Should be fixed in ede43a6.
