### ISSUE TITLE
Can’t repost, like or report items in a feed

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#9]
I visited another user’s profile but I can't do the aforementioned things.

**Comment by wingertge** [comment]
Repost is working, but feedback should be more obvious. The other two are currently missing features. Marking this as an enhancement/missing feature.

**Comment by wingertge** [comment]
Likes implemented in d2dcfdf

**Comment by wingertge** [comment]
Made repost more obvious in 3c7c090.
Closing in favour of one for just reporting, since it's a very complex thing and I'm not sure how to implement it right now.
